name: culqi_flutter
description: Una librería que implementa el proceso de creación de token en Culqi
version: 1.0.1
homepage: https://github.com/gucodero/culqi_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  email_validator: '^2.0.1'
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: